### ISSUE TITLE
CLI Option "unknown": missingTranslationString

### ISSUE THREAD

**Issue by magicyoda** [pixari/vue-i18n-extract#213]
```
> vue-i18n-extract report --vueFiles './resources/js/**/*.?(js|vue)' --languageFiles './resources/lang-js/*.?(json|yml|yaml|js)' --remove --add --missing-translation-string

[vue-i18n-extract] CACError: Unknown option `--missingTranslationString`
    at Command.checkUnknownOptions (/var/www/ekarto-dev/node_modules/cac/dist/index.js:404:17)
    at CAC.runMatchedCommand (/var/www/ekarto-dev/node_modules/cac/dist/index.js:602:13)
    at CAC.parse (/var/www/ekarto-dev/node_modules/cac/dist/index.js:541:12)
    at Object.<anonymous> (/var/www/ekarto-dev/node_modules/vue-i18n-extract/bin/vue-i18n-extract.js:56:5)`
```

I cannot use the CLI option:
--missing-translation-string
or
--missingTranslationString

both are not recognized

**Comment by storageddd** [comment]
Hi! It's actual.
It's missing because after last updates didn't publish new package version.
@Spittal, update it, please

**Comment by maximilliangeorge** [comment]
This is still an issue.

**Comment by bartholomej** [comment]
I'm also missing this functionality and a new release.

Since it hasn't happened yet, here is a temporary workaround that might help others in the meantime:

`package.json`
```json
"vue-i18n-extract": "git+https://github.com/bartholomej/vue-i18n-extract.git#missing-translation-string-variable"
```

This fork includes the fix for the missing translation string and also adds support for [template placeholders](https://github.com/Spittal/vue-i18n-extract/pull/226).
Of course, it is only a **temporary solution** until an official release is published, but it might save some headaches for now. 
(Also for #211 #201)

That said, it's worth noting that it has already been three years since the last release 😢
