### ISSUE TITLE
Unknown option `--detect`

### ISSUE THREAD

**Issue by FAbrahamDev** [pixari/vue-i18n-extract#219]
Tested various location for detect  and spelling and i always get this error when using the cli. 

Command:   
`vue-i18n-extract report --detect "missing" --vueFiles "./src/**/*.?(js|vue)" --languageFiles "./src/locales/*.?(json|yml|yaml)"`

```bash
[vue-i18n-extract] CACError: Unknown option `--detect`
    at Command.checkUnknownOptions (frontend\node_modules\.pnpm\cac@6.7.14\node_modules\cac\dist\index.js:404:17)
    at CAC.runMatchedCommand (frontend\node_modules\.pnpm\cac@6.7.14\node_modules\cac\dist\index.js:602:13)
    at CAC.parse (frontend\node_modules\.pnpm\cac@6.7.14\node_modules\cac\dist\index.js:541:12)
    at Object.<anonymous> (frontend\node_modules\.pnpm\vue-i18n-extract@2.0.7\node_modules\vue-i18n-extract\bin\vue-i18n-extract.js:56:5)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
 ELIFECYCLE  Command failed with exit code 1.
```

Also tried ` --detect missing` and in different locations

**Comment by bechtold** [comment]
I have the same issue. Is there any progress on this? I'm on version 2.0.7.
