### ISSUE TITLE
Doesn't seem to be working at all

### ISSUE THREAD

**Issue by paulvonber** [pixari/vue-i18n-extract#62]
Maybe anyone can advice what I'm doing wrong?

public % vue-i18n-extract report -v "./**/*.?(js|vue)" -l "./locales/*.?(js|json)" | tee ./tmp/i18n-report.json

(node:43596) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:506:3)
    at tryReadSync (fs.js:331:20)
    at Object.readFileSync (fs.js:368:19)
    at /Users/Paul/.config/yarn/global/node_modules/vue-i18n-extract/dist-node/index.js:66:19
    at Array.map (<anonymous>)
    at readVueFiles (/Users/Paul/.config/yarn/global/node_modules/vue-i18n-extract/dist-node/index.js:61:22)
    at VueI18NExtract.parseVueFiles (/Users/Paul/.config/yarn/global/node_modules/vue-i18n-extract/dist-node/index.js:166:23)
    at VueI18NExtract.createI18NReport (/Users/Paul/.config/yarn/global/node_modules/vue-i18n-extract/dist-node/index.js:176:33)
    at report (/Users/Paul/.config/yarn/global/node_modules/vue-i18n-extract/dist-node/index.js:288:26)
    at run (/Users/Paul/.config/yarn/global/node_modules/vue-i18n-extract/dist-node/index.js:275:7)
(node:43596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pixari** [comment]
It looks like either the path is wrong or you don't have the right permission. Could it be?

**Comment by paulvonber** [comment]
> It looks like either the path is wrong or you don't have the right permission. Could it be?

huh seems problem was here "./**/.?(js|vue)" it somehow doesn't take all of the folders 
and this way seems to be working fine "./pages/**/.?(js|vue)"

**Comment by Spittal** [comment]
Interesting, usually the glob pattern needs a star before the `.?` so for example `/**/*.?(js|vue)`. Closing this for now, let me know if you still have an issue!

**Comment by amanpatel** [comment]
I had a vendor folder with tons of files and folders, which might have had a folder that matched the glob. This was causing this error. Hope that helps someone who might be receiving this error.
