### ISSUE TITLE
Error to run vue-i18n-extract

### ISSUE THREAD

**Issue by mohamedsml** [pixari/vue-i18n-extract#77]
I m trying to run vue-i18n-extract

`npx vue-i18n-extract report -v './resources/assets/js/**/*.vue' -l './resources/assets/js/locales/*.json'`

 but i get this error:

`
(node:16284) UnhandledPromiseRejectionWarning: Error: vueFiles glob has no files.
    at u (C:\laragon\www\project\node_modules\vue-i18n-extract\dist\vue-i18n-extract.umd.js:1:772)
    at p (C:\laragon\www\project\node_modules\vue-i18n-extract\dist\vue-i18n-extract.umd.js:1:1123)
    at v (C:\laragon\www\project\node_modules\vue-i18n-extract\dist\vue-i18n-extract.umd.js:1:3203)
    at Command.b (C:\laragon\www\project\node_modules\vue-i18n-extract\dist\vue-i18n-extract.umd.js:1:3285)
    at Command.listener [as _actionHandler] (C:\laragon\www\project\node_modules\vue-i18n-extract\node_modules\commander\index.js:413:31)
    at Command._parseCommand (C:\laragon\www\project\node_modules\vue-i18n-extract\node_modules\commander\index.js:914:14)
    at Command._dispatchSubcommand (C:\laragon\www\project\node_modules\vue-i18n-extract\node_modules\commander\index.js:865:18)
    at Command._parseCommand (C:\laragon\www\project\node_modules\vue-i18n-extract\node_modules\commander\index.js:882:12)
    at Command.parse (C:\laragon\www\project\node_modules\vue-i18n-extract\node_modules\commander\index.js:717:10)
    at Command.parseAsync (C:\laragon\www\project\node_modules\vue-i18n-extract\node_modules\commander\index.js:744:10)
(node:16284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). T
o terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
`

can you help to fix this please ?

**Comment by pixari** [comment]
I can't reproduce the bug.

Feel free to open another issue with more information if this problem persists.

**Comment by sem4phor** [comment]
I get this error, too. My System is Windows 10 An newest node.
You can just leave out the apostrophes and it works.

`npx vue-i18n-extract report -v ./resources/assets/js/**/*.vue -l ./resources/assets/js/locales/*.json`

**Comment by EmilyRosina** [comment]
Also having this problem RN on Linux :cry: 
Trying to look into why...
