### ISSUE TITLE
Stopped working in latest versions

### ISSUE THREAD

**Issue by pdcmoreira** [pixari/vue-i18n-extract#95]
I'm facing an error with versions 1.1.10 and 1.1.4:
```
> vue-i18n-extract report -v "./src/**/{*.?(js|vue),.i18nignore}" -l "./src/i18n/!(index).?(js|json|yml|yaml)"

(node:23308) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token export
    at C:\Users\myproject\node_modules\vue-i18n-extract\dist\vue-i18n-extract.umd.js:145:27
    at Array.map (<anonymous>)
    at readLangFiles (C:\Users\myproject\node_modules\vue-i18n-extract\dist\vue-i18n-extract.umd.js:133:24)
    at parseLanguageFiles (C:\Users\myproject\node_modules\vue-i18n-extract\dist\vue-i18n-extract.umd.js:198:23)
    at createI18NReport (C:\Users\myproject\node_modules\vue-i18n-extract\dist\vue-i18n-extract.umd.js:285:33)
    at Command.reportCommand (C:\Users\myproject\node_modules\vue-i18n-extract\dist\vue-i18n-extract.umd.js:297:20)
    at Command.listener [as _actionHandler] (C:\Users\myproject\node_modules\vue-i18n-extract\node_modules\commander\index.js:426:31)
    at Command._parseCommand (C:\Users\myproject\node_modules\vue-i18n-extract\node_modules\commander\index.js:1002:14)
    at Command._dispatchSubcommand (C:\Users\myproject\node_modules\vue-i18n-extract\node_modules\commander\index.js:953:18)
    at Command._parseCommand (C:\Users\myproject\node_modules\vue-i18n-extract\node_modules\commander\index.js:970:12)
(node:23308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit 
code.
```

My language files are all `.js` files exporting an object ES6-style.

Version 1.1.2 works fine.

I was trying to test other versions, but I can't install a specific version with `npm i -D vue-i18n-extract@1.1.3`, for version 1.1.3 and from version 1.1.5 up to version 1.1.9. Installing version 1.1.10 works fine again with this syntax.

**[edit]**
I just noticed you decided to remove support for `.js` files: https://github.com/pixari/vue-i18n-extract/commit/df69db56cf08367538b0d634d7c2c8159528717d
Is the reasoning for this decision discussed anywhere?

**Comment by crazymind** [comment]
same here

**Comment by pixari** [comment]
Yes @pdcmoreira, you are right.

Unfortunately supporting JS files caused other problems we couldn't manage to solve.

I'll try to find a solution.

**Comment by pixari** [comment]
I created an issue: https://github.com/pixari/vue-i18n-extract/issues/109
